// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $bank_index from "./routes/bank/index.tsx";
import * as $consumer_index from "./routes/consumer/index.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $BankPortal from "./islands/BankPortal.tsx";
import * as $ConsumerPortal from "./islands/ConsumerPortal.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $DemoBar from "./islands/DemoBar.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/bank/index.tsx": $bank_index,
    "./routes/consumer/index.tsx": $consumer_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/BankPortal.tsx": $BankPortal,
    "./islands/ConsumerPortal.tsx": $ConsumerPortal,
    "./islands/Counter.tsx": $Counter,
    "./islands/DemoBar.tsx": $DemoBar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
